modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
An OpenCode client for Minecraft single player with game pause integration
'''
authors="OpenCode"
displayURL="https://github.com/opencodedev/opencode"

[[mixins]]
config="opencode.mixins.json"

[[dependencies.opencode]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.opencode]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
